{username, ...}: {
  systemd.user.tmpfiles.rules = [
    "d /home/${username}/Scripts 0755 ${username} users - -"
    "d /home/${username}/Studio/OBS/config/obs-studio/ 0755 ${username} users - -"
    "d /home/${username}/Documents/workspace/linux 0755 ${username} users - -"
    "d /home/${username}/Documents/workspace/virtualmachines/windows 0755 ${username} users - -"
    "d /home/${username}/Documents/workspace/virtualmachines/linux 0755 ${username} users - -"
    "d /home/${username}/Documents/workspace/virtualmachines/mac 0755 ${username} users - -"
    "d /home/${username}/Documents/workspace/docker-configs/resources 0750 ${username} users - -"
    "d /home/${username}/Documents/workspace/docker-configs/composes 0755 ${username} users - -"
    "d /home/${username}/Documents/workspace/lab 0755 ${username} users - -"
    "d /home/${username}/Documents/workspace/github 0755 ${username} users - -"
    "d /home/${username}/Documents/workspace/bitbucket 0755 ${username} users - -"
    "d /home/${username}/Documents/workspace/gitlab 0755 ${username} users - -"
    "d /home/${username}/Documents/workspace/scripts 0755 ${username} users - -"
    "d /home/${username}/Videos/Animes/movies 0755 ${username} users - -"
    "d /home/${username}/Videos/Animes/series 0755 ${username} users - -"
    "d /home/${username}/Videos/Animes/OVAs 0755 ${username} users - -"
    "d /home/${username}/Videos/Series 0755 ${username} users - -"
    "d /home/${username}/Videos/Movies 0755 ${username} users - -"
    "d /home/${username}/Videos/Youtube 0755 ${username} users - -"
    "d /home/${username}/Videos/Youtube/Tutorials 0755 ${username} users - -"
    "d /home/${username}/Music/playlists 0755 ${username} users - -"
    "d /home/${username}/Music/albums 0755 ${username} users - -"
    "d /home/${username}/Music/singles 0755 ${username} users - -"
    "d /home/${username}/Music/artits 0755 ${username} users - -"
    "d /home/${username}/Music/downloads 0755 ${username} users - -"
    "d /home/${username}/Music/records 0755 ${username} users - -"
    "d /home/${username}/Games 0755 ${username} users - -"
    "d /home/${username}/Quickemu/nixos-desktop 0755 ${username} users - -"
    "d /home/${username}/Quickemu/nixos-console 0755 ${username} users - -"
    "d /home/${username}/Syncthing 0755 ${username} users - -"
    "d /home/${username}/Pictures/family 0755 ${username} users - -"
    "d /home/${username}/Pictures/backup 0755 ${username} users - -"
    "d /home/${username}/Pictures/phones 0755 ${username} users - -"
    "d /home/${username}/Pictures/wallpapers 0755 ${username} users - -"
    "d /home/${username}/Pictures/resources 0755 ${username} users - -"
    "d /home/${username}/Zero 0755 ${username} users - -"
    #"d /home/${username}/Volatile/Vorta 0755 ${username} users - -"
    "L+ /home/${username}/.config/obs-studio/ - - - - /home/${username}/Studio/OBS/config/obs-studio/"
  ];
}
